### ISSUE TITLE
Konnektor proxy not needed on localhost

### ISSUE THREAD

**Issue by KlausNie** [oviva-ag/epa4all-client#4]
### The overall issue
wireguard, used as a kernel space implementation (native wireguard https://www.wireguard.com/install/ or the wireguard image with access to the host network stack https://hub.docker.com/r/linuxserver/wireguard/) makes the VPN connection available to the whole host.

This is problematic in a world of docker compose, where multiple containers are running on the same host machine and even more so in k8s where we might not even know which other containers are running on that same node.

Also, a wrong wireguard configuration (e.g. mounting an empty folder instead of a .conf) into a wireguard container gives wireguard the chance to brick your host's network, removing network capabilty of the machine/node until you restart it.

It becomes more problematic when you want to automatically have multiple vpns on the same host.

### One solution
Keep wireguard in userspace (e.g. https://github.com/qdm12/gluetun). The basic idea is, to keep wireguard (epa4all-vpn) isolated to the container, and let the epa4all-rest service use the epa4all-vpn's network stack.
This makes handling wireguard connections a lot easier!

Example `docker-compose.yml`:
```yaml
services:
  epa4all-rest:
    container_name: epa4all-rest
    image: epa4all-rest-service:v1.0.0-SNAPSHOT
    ports:
        - '127.0.0.1:8099:8080'
    volumes:
        - ./vKon_Client_XXX.p12:/credentials.p12
    environment:
        - EPA4ALL_KONNEKTOR_URI=https://10.156.145.103:443
        - EPA4ALL_ENVIRONMENT=RU
        - EPA4ALL_PROXY_ADDRESS=127.0.0.1
        - EPA4ALL_CREDENTIALS_PATH=/credentials.p12

        - EPA4ALL_WORKPLACE_ID=test-arbeitsplatz
        - EPA4ALL_CLIENT_SYSTEM_ID=test-api
        - EPA4ALL_MANDANT_ID=test-mandant
        - EPA4ALL_USER_ID=admin

  epa4all-vpn:
    container_name: epa4all-vpn
    image: qmcgaw/gluetun:v3
    cap_add:
        - NET_ADMIN
    network_mode: "service:epa4all-rest"
    environment:
        - VPN_SERVICE_PROVIDER=custom
        - VPN_TYPE=wireguard
        - WIREGUARD_IMPLEMENTATION=userspace
        - DNS_KEEP_NAMESERVER=on
        - PUBLICIP_ENABLED=off

        - HEALTH_TARGET_ADDRESS=10.156.145.103:443
        - HEALTH_VPN_DURATION_INITIAL=24h
        - HEALTH_VPN_DURATION_ADDITION=24h
        - HEALTH_SUCCESS_WAIT_DURATION=24h
    volumes:
        - ./VPN_XXX.conf:/gluetun/wireguard/wg0.conf
    healthcheck:
        test: "ping -c 1 10.156.145.103:443 || exit 1"
        interval: 1s
        retries: 1
        timeout: 5s
        start_period: 5s
```

### A small configuration change needed

This works network-wise, but there is an issue with the proxy setup within the epa4all-client.
I cannot say, that I 100% understood why a proxy is needed, in the case of the Konnektor (https://github.com/oviva-ag/epa4all-client/blob/f23ea2b268a1e91ca477ad1c6270bcf3b4263594/konnektor/konnektor-client/src/main/java/com/oviva/epa/client/konn/KonnektorConnectionFactoryBuilder.java#L129) AND the Epa4AllClient (https://github.com/oviva-ag/epa4all-client/blob/f23ea2b268a1e91ca477ad1c6270bcf3b4263594/epa4all-rest-service/src/main/java/com/oviva/telematik/epa4all/restservice/Epa4allClientService.java#L101), but I've found, that the docker-compose above only works when I remove the 2 `conconfigureProxyIfEnabledfig` calls in https://github.com/oviva-ag/epa4all-client/blob/main/konnektor/konnektor-client/src/main/java/com/oviva/epa/client/konn/internal/KonnektorConnectionFactoryImpl.java :
- https://github.com/oviva-ag/epa4all-client/blob/f23ea2b268a1e91ca477ad1c6270bcf3b4263594/konnektor/konnektor-client/src/main/java/com/oviva/epa/client/konn/internal/KonnektorConnectionFactoryImpl.java#L105
- https://github.com/oviva-ag/epa4all-client/blob/f23ea2b268a1e91ca477ad1c6270bcf3b4263594/konnektor/konnektor-client/src/main/java/com/oviva/epa/client/konn/internal/KonnektorConnectionFactoryImpl.java#L151

I found a rather non-invasive way on how to handle this, and would create a PR shortly
